substitutions:
  device: esp-pmsa-01
  name: "ESP-PMSA 01"
  location: Garage
  reboot_timeout: 15min
  update_interval: 30s
  log_level: DEBUG
  psensor_type: PMSX003

esphome:
  name: "${device}"
  friendly_name: "${name}"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended

packages:
  - !include common/base.yaml
  - !include common/wifi.yaml

logger:
  level: DEBUG

# configure uart
uart:
  id: uart_pmsa
  rx_pin: GPIO1
  tx_pin: GPIO0
  baud_rate: 9600

# configure i2c
i2c:
  id: i2c1
  sda: GPIO4
  scl: GPIO5

# sensors
sensor:
  - platform: pmsx003
    type: ${psensor_type}
    uart_id: uart_pmsa
    update_interval: 60s
    pm_1_0:
      name: "PM1.0 µG/m3"
    pm_2_5:
      name: "PM2.5 µG/m3"
    pm_10_0:
      name: "PM10 µG/m3"

# PMSA003 sensor control GPIOs
switch:
    # PMSX003 standby/sleep mode control
  - platform: gpio
    id: pms_set
    name: "${name} ${psensor_type} Enable"
    pin:
      number: GPIO2
      mode: OUTPUT
    restore_mode: ALWAYS_ON

  - platform: gpio
    name: "${name} ${psensor_type} Reset"
    id: pms_rst
    pin:
      number: GPIO3
      inverted: true
      mode: OUTPUT
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: pms_rst


