substitutions:
  device: lounge-bme
  name: "Lounge Environment Sensor"
  area: Nowhere
  update_interval: 60s

  reboot_timeout: 15min
  ap_timeout: 0s # disable automatic AP mode

  log_level: INFO

esphome:
  name: "${device}"
  friendly_name: "${name}"
  area: ${area}

esp32:
  # m5stack atom matrix
  variant: esp32
  framework:
    type: esp-idf

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi.yaml
  web_server: !include common/web_server.yaml
  rgb_status: !include
    file: common/rgb/status.yaml
    vars:
      status_rgb_count: 25
      status_button_gpio: GPIO39
      status_rgb_gpio: GPIO27
      # turning this up too high is not only eye-searing but could damage the unit
      status_rgb_brt_max: 25%
  # mpu6886_accel: !include common/m5stack/mpu6886-accel.yaml
  bme680: !include
    file: devices/sensor/bme680.yaml
    vars:
      bme_i2c_id: i2c0
      bme_i2c_addr: 0x77
      bme_bsec2_id: bme680
      bme_sample_rate: LP
      bme_operating_age: 28d
      update_interval: ${update_interval}

# enable debug logging
logger:
  level: ${log_level}

# enable flash persistence
preferences:
  flash_write_interval: 1min

# allow this device to go offline without going unavailable in Home Assistant
deep_sleep:

# BLE tracker to see other devices
esp32_ble_tracker:

# BT proxy for home assistant
bluetooth_proxy:
  active: true
  connection_slots: 3

# i2c for bosch BME680 and MPU6886 accelerometer
i2c:
  - id: i2c0
    sda: GPIO25
    scl: GPIO21
    scan: true
    frequency: 400kHz

# some sensors
sensor:
  # internal temperature sensor, cause why not
  - platform: internal_temperature
    id: cpu_temp
    name: "CPU Temperature"
    device_class: temperature
    entity_category: diagnostic
