substitutions:
  device: m5solar
  name: "Solar Inverter"
  update_interval: 60s

  reboot_timeout: 15min
  ap_timeout: 0s # disable automatic AP mode

  log_level: INFO

esphome:
  name: "${device}"
  friendly_name: "${name}"

esp32:
  board: m5stack-atoms3
  framework:
    type: esp-idf
    version: recommended

packages:
  base: !include common/base.yaml
  wifi: !include
    file:  common/wifi.yaml
    vars:
      wifi_power_save_mode: NONE # this prevents use of BLE
  web_server: !include common/web_server.yaml
  m5stack_status: !include
    file: common/rgb/status.yaml
    vars:
      status_button_gpio: GPIO41
      status_rgb_gpio: GPIO35
      status_rgb_brt_max: 75%
  solis: !include
    file: devices/solis-modbus-inv.yaml
    vars:
      solis_modbus_bus: modbus_bus
      solis_modbus_addr: 1
      solis_time_source: network_time
  modbus_bridge: !include devices/modbus-bridge.yaml

# enable debug logging
logger:
  level: ${log_level}

# allow this device to go offline without going unavailable in Home Assistant
deep_sleep:

# UART for Modbus RTU
uart:
  id: modbus_uart
  tx_pin: GPIO2
  rx_pin: GPIO1
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

modbus:
  id: modbus_bus
  uart_id: modbus_uart
  send_wait_time: 250ms

modbus_controller:
  - id: !extend modbus_con_solis
    on_offline:
      then:
        status.push:
          trigger_id: status_orange_pulse
    on_online:
      then:
        status.pop:
          trigger_id: status_orange_pulse
