substitutions:
  device: snifferboi
  name: "Particle Sniffer"

esphome:
  name: "${device}"
  friendly_name: "${name}"

esp8266:
  board: d1_mini

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi.yaml

# Make sure logging is not using the serial port
logger:
  baud_rate: 0
  level: DEBUG

# configure PMSA003
uart:
  # esp8266 UART0 must be on GPIO1/3 or GPIO15/13
  tx_pin: GPIO15 # arduino pin D8
  rx_pin: GPIO13 # arduino pin D7
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    id: pmsa003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"

# onboard LED
status_led:
  pin:
    number: D4
    inverted: True
