defaults:
  bme_i2c_bus: i2c0
  bme_i2c_addr: 0x76
  bme_bsec2_id: bme680
  bme_operating_age: 28d
  bme_accuracy_decimals: 2
  bme_sample_rate: LP # 3 seconds, ULP for 5 mins
  bme_temp_offset: 0.0
  update_interval: ${update_interval}

# bosch bme680 driver using BSEC2
bme68x_bsec2_i2c:
  id: ${bme_bsec2_id}
  model: bme680
  i2c_id: ${bme_i2c_bus}
  address: ${bme_i2c_addr}
  operating_age: ${bme_operating_age}
  sample_rate: ${bme_sample_rate}
  temperature_offset: ${bme_temp_offset}

sensor:
  # BME68x sensors
  - platform: bme68x_bsec2
    bme68x_bsec2_id: ${bme_bsec2_id}
    temperature:
      id: ${bme_bsec2_id}_temp
      name: "Temperature"
      icon: mdi:thermometer
      device_class: temperature
      state_class: measurement
      accuracy_decimals: ${bme_accuracy_decimals}
    pressure:
      id: ${bme_bsec2_id}_pressure
      name: "Pressure"
      icon: mdi:weather-windy
      device_class: atmospheric_pressure
      state_class: measurement
      accuracy_decimals: ${bme_accuracy_decimals}
    humidity:
      id: ${bme_bsec2_id}_humidity
      name: "Humidity"
      icon: mdi:water-percent
      device_class: humidity
      state_class: measurement
      accuracy_decimals: ${bme_accuracy_decimals}
    co2_equivalent:
      id: ${bme_bsec2_id}_co2_equiv
      name: "CO2 Equivalent"
      icon: mdi:molecule-co2
      device_class: carbon_dioxide
      state_class: measurement
      accuracy_decimals: ${bme_accuracy_decimals}
    breath_voc_equivalent:
      id: ${bme_bsec2_id}_breath_voc_equiv
      name: "Breath VOC Equivalent"
      icon: mdi:scent
      device_class: volatile_organic_compounds
      state_class: measurement
      accuracy_decimals: ${bme_accuracy_decimals}

    iaq:
      id: ${bme_bsec2_id}_iaq
      name: "IAQ"
      icon: mdi:air-filter
      device_class: aqi
      state_class: measurement
      accuracy_decimals: 0
    iaq_static:
      id: ${bme_bsec2_id}_iaq_static
      name: "IAQ Static"
      icon: mdi:air-filter
      device_class: aqi
      state_class: measurement
      accuracy_decimals: 0
    iaq_accuracy:
      id: ${bme_bsec2_id}_iaq_accuracy_int
      name: "IAQ Accuracy Value"
      icon: mdi:chemical-weapon
      entity_category: diagnostic
      accuracy_decimals: 0

    gas_resistance:
      id: ${bme_bsec2_id}_gas_resistance
      name: "Gas Resistance"
      device_class: gas
      state_class: measurement
      entity_category: diagnostic
      accuracy_decimals: 1

text_sensor:
  - platform: bme68x_bsec2
    bme68x_bsec2_id: ${bme_bsec2_id}
    iaq_accuracy:
      id: ${bme_bsec2_id}_iaq_accuracy_str
      name: "IAQ Accuracy"
      icon: "mdi:chemical-weapon"

  - platform: template
    name: "IAQ Classification"
    icon: "mdi:air-filter"
    lambda: |-
      int iaq_val = int(id(${bme_bsec2_id}_iaq).state);
      if ( iaq_val <= 50) {
        return {"Excellent"};
      } else if ( iaq_val <= 100) {
        return {"Good"};
      } else if (  iaq_val <= 150) {
        return {"Lightly polluted"};
      } else if (iaq_val <= 200) {
        return {"Moderately polluted"};
      } else if (iaq_val <= 250) {
        return {"Heavily polluted"};
      } else if (iaq_val <= 350) {
        return {"Severely polluted"};
      } else if (iaq_val >= 351) {
        return {"Extremely polluted"};
      } else {
        return {"Invalid"};
      }
