substitutions:
  devname: "powerpalpal"
  devname_full: "powerpalpal"
  powerpal_mac: "E3:4E:B2:C1:BE:6B"

esphome:
  name: powerpalpal

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# load powerpal sniff
external_components:
  - source: github://WeekendWarrior1/esphome@powerpal_ble
    # requires ble_client because I had to add some small features to authenticate properly
    components: [ ble_client, powerpal_ble ]

# Enable logging
logger:
  level: VERBOSE
  logs:
    esp32_ble_tracker: INFO

# Enable Home Assistant API
api:

ota:
  password: "ff07e32a8aabe6e404749419774dec07"

wifi:
  power_save_mode: light
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass
      priority: 1
  ap:
    ssid: "powerpalpal"
    password: !secret ap_pass
captive_portal:

# things required for powerpal
http_request:
esp32_ble_tracker:
ble_client:
  - mac_address: ${powerpal_mac}
    id: powerpal

sensor:
  # RSSI based on MAC address
  - platform: ble_rssi
    mac_address: ${powerpal_mac}
    name: "BLE RSSI for Powerpal"
  - platform: powerpal_ble
    ble_client_id: powerpal
    power:
      name: "Powerpal Power"
    energy:
      name: "Powerpal Total Energy"
    battery_level:
      name: "Powerpal Battery"
    pairing_code: 690136
    notification_interval: 1
    pulses_per_kwh: 800
    
# Platform Status sensor
binary_sensor:
  - platform: status
    name: "${devname_full} status"

status_led:
  pin: GPIO2
