---
defaults:
  log_level: INFO

# Enable logging
logger:
  level: ${log_level}

# enable OTA
ota:
  - platform: esphome
    password: !secret ota_password

# enable API and home assistant time source
packages:
  esphome_api: !include api.yaml
  hassio_time: !include hassio/time.yaml

# Platform Status sensors
sensor:
  - platform: uptime
    name: Uptime
    icon: mdi:timer-outline
    entity_category: diagnostic

binary_sensor:
  - platform: status
    id: device_ok
    name: Status
    icon: mdi:information
    entity_category: diagnostic

# remote reboot switch
switch:
  - platform: restart
    id: restart_switch
    name: Restart Device
    icon: mdi:restart
    entity_category: config
    restore_mode: ALWAYS_OFF

  - platform: factory_reset
    id: factory_reset_switch
    name: Factory Reset
    icon: mdi:restart-alert
    entity_category: config
    restore_mode: ALWAYS_OFF
    disabled_by_default: true
